version: 2

multi-ecosystem-groups:
  maintenance:
    schedule:
      interval: "monthly"
      time: "05:15"
      timezone: "America/Bogota"

updates:
  # Composer (PHP)
  - package-ecosystem: "composer"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "maintenance"
    labels:
      - "php"
      - "dependencies"
